<template>
  <div class="article-container">
    <article>
      <h1>{{$t('REGISTER.TITLE')}}</h1>
      <h4>{{$t('REGISTER.CONTENT')}}</h4>
      <h3>{{$t('REGISTER.ARTICLE_1')}}</h3>
      <p>{{$t('REGISTER.CONTENT_1_1')}}</p>
      <p>{{$t('REGISTER.CONTENT_1_2')}}</p>
      <p>{{$t('REGISTER.CONTENT_1_3')}}</p>
      <p>{{$t('REGISTER.CONTENT_1_4')}}</p>
      <h3>{{$t('REGISTER.ARTICLE_2')}}</h3>
      <p>{{$t('REGISTER.CONTENT_2_1')}}</p>
      <p>{{$t('REGISTER.CONTENT_2_2')}}</p>
      <span>{{$t('REGISTER.CONTENT_2_2_1')}}</span>
      <span>{{$t('REGISTER.CONTENT_2_2_2')}}</span>
      <h3>{{$t('REGISTER.ARTICLE_3')}}</h3>
      <p>{{$t('REGISTER.CONTENT_3_1')}}</p>
      <p>{{$t('REGISTER.CONTENT_3_2')}}</p>
      <p>{{$t('REGISTER.CONTENT_3_3')}}</p>
      <p>{{$t('REGISTER.CONTENT_3_4')}}</p>
      <p>{{$t('REGISTER.CONTENT_3_5')}}</p>
      <p>{{$t('REGISTER.CONTENT_3_6')}}</p>
      <h3>{{$t('REGISTER.ARTICLE_4')}}</h3>
      <p>{{$t('REGISTER.CONTENT_4_1')}}</p>
      <span>{{$t('REGISTER.CONTENT_4_1_1')}}</span>
      <span>{{$t('REGISTER.CONTENT_4_1_2')}}</span>
      <span>{{$t('REGISTER.CONTENT_4_1_3')}}</span>
      <span>{{$t('REGISTER.CONTENT_4_1_4')}}</span>
      <span>{{$t('REGISTER.CONTENT_4_1_5')}}</span>
      <span>{{$t('REGISTER.CONTENT_4_1_6')}}</span>
      <span>{{$t('REGISTER.CONTENT_4_1_7')}}</span>
      <span>{{$t('REGISTER.CONTENT_4_1_8')}}</span>
      <span>{{$t('REGISTER.CONTENT_4_1_9')}}</span>
      <p>{{$t('REGISTER.CONTENT_4_2')}}</p>
      <p>{{$t('REGISTER.CONTENT_4_3')}}</p>
      <p>{{$t('REGISTER.CONTENT_4_4')}}</p>
      <h3>{{$t('REGISTER.ARTICLE_5')}}</h3>
      <p>{{$t('REGISTER.CONTENT_5_1')}}</p>
      <p>{{$t('REGISTER.CONTENT_5_2')}}</p>
      <h3>{{$t('REGISTER.ARTICLE_6')}}</h3>
      <p>{{$t('REGISTER.CONTENT_6_1')}}</p>
      <p>{{$t('REGISTER.CONTENT_6_2')}}</p>
      <p>{{$t('REGISTER.CONTENT_6_3')}}</p>
      <h3>{{$t('REGISTER.ARTICLE_7')}}</h3>
      <p>{{$t('REGISTER.CONTENT_7_1')}}</p>
      <span>{{$t('REGISTER.CONTENT_7_1_1')}}</span>
      <span>{{$t('REGISTER.CONTENT_7_1_2')}}</span>
      <span>{{$t('REGISTER.CONTENT_7_1_3')}}</span>
      <span>{{$t('REGISTER.CONTENT_7_1_4')}}</span>
      <h3>{{$t('REGISTER.ARTICLE_8')}}</h3>
      <p>{{$t('REGISTER.CONTENT_8_1')}}</p>
      <p>{{$t('REGISTER.CONTENT_8_2')}}</p>
      <p>{{$t('REGISTER.CONTENT_8_3')}}</p>
      <p>{{$t('REGISTER.CONTENT_8_4')}}</p>
      <p>{{$t('REGISTER.CONTENT_8_5')}}</p>
      <p>{{$t('REGISTER.CONTENT_8_6')}}</p>
      <p>{{$t('REGISTER.CONTENT_8_7')}}</p>
      <h3>{{$t('REGISTER.ARTICLE_9')}}</h3>
      <p>{{$t('REGISTER.CONTENT_9_1')}}</p>
      <p>{{$t('REGISTER.CONTENT_9_2')}}</p>
      <p>{{$t('REGISTER.CONTENT_9_3')}}</p>
      <h3>{{$t('REGISTER.ARTICLE_10')}}</h3>
      <p>{{$t('REGISTER.CONTENT_10')}}</p>
      <h3>{{$t('REGISTER.ARTICLE_11')}}</h3>
      <p>{{$t('REGISTER.CONTENT_11_1')}}</p>
      <p>{{$t('REGISTER.CONTENT_11_2')}}</p>
      <h3>{{$t('REGISTER.ARTICLE_12')}}</h3>
      <p>{{$t('REGISTER.CONTENT_12_1')}}</p>
      <p>{{$t('REGISTER.CONTENT_12_2')}}</p>
    </article>
  </div>
</template>

<script>
export default {
  name: 'registration',
}
</script>
